// 100 short study motivations rotated in the chat empty-state
export const MOTIVATIONS = [
  "Ready to learn?",
  "What are we mastering today?",
  "Let's make studying feel effortless.",
  "One concept at a time.",
  "Curiosity is your superpower.",
  "Small steps, big breakthroughs.",
  "Ask boldly. Learn deeply.",
  "Turn confusion into clarity.",
  "What's the topic on your mind?",
  "Let's decode something today.",
  "Understanding beats memorising.",
  "Every question moves you forward.",
  "Focus mode: engaged.",
  "You + Nextudy = unstoppable.",
  "Which chapter are we cracking?",
  "Study smarter, not harder.",
  "Let's build your knowledge stack.",
  "Momentum starts with one prompt.",
  "Bring me your toughest question.",
  "Ideas love company — share yours.",
  "Let's turn notes into knowledge.",
  "What's confusing you today?",
  "Ready for a lightbulb moment?",
  "Let's simplify the complicated.",
  "Feed me your PDF or your doubts.",
  "Deep work, light effort.",
  "Learning loves repetition.",
  "Let's make it click.",
  "Progress compounds. Start now.",
  "What would future-you thank you for?",
  "Time to level up.",
  "Curiosity in, clarity out.",
  "Say the question out loud.",
  "Let's find the pattern.",
  "Break it down together.",
  "One prompt closer to mastery.",
  "Your midnight study buddy.",
  "Note anything. Ask everything.",
  "Turn overwhelm into outline.",
  "Which formula is haunting you?",
  "Let's map it out.",
  "Every expert started here.",
  "You're closer than you think.",
  "Let's make the abstract obvious.",
  "One clear question changes everything.",
  "Learning is a workout for the mind.",
  "Ready to synthesise?",
  "Bring me a paragraph, I'll bring insight.",
  "Let's rewrite that in plain English.",
  "Focus. Ask. Learn. Repeat.",
  "Give me a topic — I'll give you a summary.",
  "What's the deadline we're beating?",
  "Small wins, stacked daily.",
  "Ask like you mean it.",
  "Let's decode the jargon.",
  "You've got this. I've got context.",
  "Sharpen the concept.",
  "Turn your notes into insight.",
  "Learning is the ultimate cheat code.",
  "Let's make revision fun.",
  "What theorem are we taming?",
  "Explain it to me — I'll explain it back better.",
  "One diagram from a breakthrough.",
  "Test yourself. Trust the process.",
  "Study crew of one, powered by AI.",
  "Let's turn slides into stories.",
  "Ready to make it stick?",
  "What's the exam we're crushing?",
  "Every A starts with a question.",
  "Show me the chapter, I'll show you the map.",
  "Let's translate lectures into logic.",
  "Notebooks open, mind open.",
  "One prompt away from that eureka.",
  "The best students ask the most questions.",
  "Focused sessions build fluent minds.",
  "Let's make learning your default.",
  "Study less. Learn more.",
  "Ready when you are.",
  "Bring me the confusion.",
  "One idea. Full understanding.",
  "Turn passive reading into active recall.",
  "Which subject is on the docket?",
  "Let's untangle it together.",
  "Master mode: initialised.",
  "Give me your worst — I'll give you clarity.",
  "Learning speed unlocked.",
  "Simple explanations. Deep understanding.",
  "Every note deserves a second read.",
  "Ready to outline something ambitious?",
  "The night is young. So is your curiosity.",
  "Coffee optional, curiosity required.",
  "Let's make revision addictive.",
  "One topic, fully understood.",
  "Turn today's confusion into tomorrow's confidence.",
  "Let's ace the next quiz.",
  "The syllabus won't know what hit it.",
  "Ready to think out loud?",
  "Let's make studying feel like flow.",
  "A better question builds a better student.",
  "Show up. Ask. Grow.",
  "Your knowledge, upgraded.",
];
