/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsNewRouteImport } from './routes/whats-new'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrewsRouteImport } from './routes/crews'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWelcomeOnboardingRouteImport } from './routes/api/public/welcome-onboarding'
import { Route as ApiPublicInviteMemberRouteImport } from './routes/api/public/invite-member'
import { Route as ApiPublicCreateCheckoutRouteImport } from './routes/api/public/create-checkout'

const WhatsNewRoute = WhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewsRoute = CrewsRouteImport.update({
  id: '/crews',
  path: '/crews',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWelcomeOnboardingRoute =
  ApiPublicWelcomeOnboardingRouteImport.update({
    id: '/api/public/welcome-onboarding',
    path: '/api/public/welcome-onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInviteMemberRoute = ApiPublicInviteMemberRouteImport.update({
  id: '/api/public/invite-member',
  path: '/api/public/invite-member',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreateCheckoutRoute = ApiPublicCreateCheckoutRouteImport.update({
  id: '/api/public/create-checkout',
  path: '/api/public/create-checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/crews': typeof CrewsRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/whats-new': typeof WhatsNewRoute
  '/api/public/create-checkout': typeof ApiPublicCreateCheckoutRoute
  '/api/public/invite-member': typeof ApiPublicInviteMemberRoute
  '/api/public/welcome-onboarding': typeof ApiPublicWelcomeOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/crews': typeof CrewsRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/whats-new': typeof WhatsNewRoute
  '/api/public/create-checkout': typeof ApiPublicCreateCheckoutRoute
  '/api/public/invite-member': typeof ApiPublicInviteMemberRoute
  '/api/public/welcome-onboarding': typeof ApiPublicWelcomeOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/crews': typeof CrewsRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/whats-new': typeof WhatsNewRoute
  '/api/public/create-checkout': typeof ApiPublicCreateCheckoutRoute
  '/api/public/invite-member': typeof ApiPublicInviteMemberRoute
  '/api/public/welcome-onboarding': typeof ApiPublicWelcomeOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/crews'
    | '/dashboard'
    | '/feedback'
    | '/profile'
    | '/settings'
    | '/subscriptions'
    | '/whats-new'
    | '/api/public/create-checkout'
    | '/api/public/invite-member'
    | '/api/public/welcome-onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/crews'
    | '/dashboard'
    | '/feedback'
    | '/profile'
    | '/settings'
    | '/subscriptions'
    | '/whats-new'
    | '/api/public/create-checkout'
    | '/api/public/invite-member'
    | '/api/public/welcome-onboarding'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/crews'
    | '/dashboard'
    | '/feedback'
    | '/profile'
    | '/settings'
    | '/subscriptions'
    | '/whats-new'
    | '/api/public/create-checkout'
    | '/api/public/invite-member'
    | '/api/public/welcome-onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CrewsRoute: typeof CrewsRoute
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  WhatsNewRoute: typeof WhatsNewRoute
  ApiPublicCreateCheckoutRoute: typeof ApiPublicCreateCheckoutRoute
  ApiPublicInviteMemberRoute: typeof ApiPublicInviteMemberRoute
  ApiPublicWelcomeOnboardingRoute: typeof ApiPublicWelcomeOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whats-new': {
      id: '/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof WhatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crews': {
      id: '/crews'
      path: '/crews'
      fullPath: '/crews'
      preLoaderRoute: typeof CrewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/welcome-onboarding': {
      id: '/api/public/welcome-onboarding'
      path: '/api/public/welcome-onboarding'
      fullPath: '/api/public/welcome-onboarding'
      preLoaderRoute: typeof ApiPublicWelcomeOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/invite-member': {
      id: '/api/public/invite-member'
      path: '/api/public/invite-member'
      fullPath: '/api/public/invite-member'
      preLoaderRoute: typeof ApiPublicInviteMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-checkout': {
      id: '/api/public/create-checkout'
      path: '/api/public/create-checkout'
      fullPath: '/api/public/create-checkout'
      preLoaderRoute: typeof ApiPublicCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CrewsRoute: CrewsRoute,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  WhatsNewRoute: WhatsNewRoute,
  ApiPublicCreateCheckoutRoute: ApiPublicCreateCheckoutRoute,
  ApiPublicInviteMemberRoute: ApiPublicInviteMemberRoute,
  ApiPublicWelcomeOnboardingRoute: ApiPublicWelcomeOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
